name: build

on:
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-22.04

    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Coursier
      uses: actions/cache@v4
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}

    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run Tests
      run: sbt -Dsbt.color=always -Dsbt.supershell=false scalafmtCheck scalafmtSbtCheck headerCheckAll test IntegrationTest/test

    - name: Debug Sonatype credentials
      run: |
        echo "SONATYPE_USERNAME=${{ secrets.SONATYPE_USERNAME }}"
        echo "SONATYPE_PASSWORD is set: ${ { secrets.SONATYPE_PASSWORD != '' }}"
        echo "GPG_SECRET is set: ${ { secrets.PGP_SECRET != '' }}"
        echo "GPG_PASSPHRASE is set: ${ { secrets.PGP_PASSPHRASE != '' }}"
